name: Deploy app

on:
  #push:
  # branches:
  #   - main
  pull_request:
    branches:
      - main

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - name: Cloner le repo
        uses: actions/checkout@v3

      - name: Connexion au ghcr
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Image repo
        run: echo "IMAGE_REPO=$(echo '${{ github.repository }}' | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV

      - name: Build et Push Backend

        run: |
          docker build -t ghcr.io/$IMAGE_REPO/backend:latest services/backend
          docker push ghcr.io/$IMAGE_REPO/backend:latest

      - name: Build et Push Frontend
        run: |
          docker build -t ghcr.io/$IMAGE_REPO/frontend:latest services/frontend
          docker push ghcr.io/$IMAGE_REPO/frontend:latest

      - name: Build et Push Kafka Producers
        run: |
          docker build -t ghcr.io/$IMAGE_REPO/api-climatologique:latest services/api_climatologique_producer
          docker push ghcr.io/$IMAGE_REPO/api-climatologique:latest

          docker build -t ghcr.io/$IMAGE_REPO/api-observations:latest services/api_observations_producer
          docker push ghcr.io/$IMAGE_REPO/api-observations:latest

          docker build -t ghcr.io/$IMAGE_REPO/api-vigilance:latest services/api_vigilance_producer
          docker push ghcr.io/$IMAGE_REPO/api-vigilance:latest

      - name: Build et Push Consumers
        run: |
          docker build -t ghcr.io/$IMAGE_REPO/mongo-consumer:latest services/mongo_consumer
          docker push ghcr.io/$IMAGE_REPO/mongo-consumer:latest

          docker build -t ghcr.io/$IMAGE_REPO/redis-consumer:latest services/redis_consumer
          docker push ghcr.io/$IMAGE_REPO/redis-consumer:latest

      - name: Build et Push API Export
        run: |
          docker build -t ghcr.io/$IMAGE_REPO/api-export:latest services/api_export
          docker push ghcr.io/$IMAGE_REPO/api-export:latest

  # Étape 3 : Déploiement sur EC2
  deploy:
    needs: build-and-push
    runs-on: ubuntu-latest
    steps:
      - name: Cloner le repo
        uses: actions/checkout@v3

      - name: Déploiement sur EC2 AWS avec Docker Compose
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            cd ~/Meteo-France-Platform-IoT
            git pull origin main
            docker login -u ${{ github.actor }} -p ${{ secrets.GITHUB_TOKEN }} ghcr.io
            docker compose pull
            docker compose up -d
            docker system prune -f
